"""SQLAlchemy models for the intraday trading module.

Two tables:
  - `intraday_plans`: one row per generated plan (one per ticker per day).
  - `intraday_outcomes`: one row per plan once next-day OHLC is available.
      outcome = TP1 / TP2 / SL / EOD / OPEN_GAP (which side hit first).

Both tables live in the same SQLite database as the rest of StockAI
(``stockai.data.database``) so the user gets a single source of truth.
"""

from __future__ import annotations

from datetime import date as _date, datetime

from sqlalchemy import (
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from stockai.data.models import Base


class IntradayPlanRow(Base):
    """A single intraday plan as generated by `stockai intraday plan/report`."""

    __tablename__ = "intraday_plans"

    id = Column(Integer, primary_key=True)
    # The trading day the plan is FOR (e.g. plan generated 28-Jun FOR 29-Jun).
    plan_date = Column(Date, nullable=False, index=True)
    # The trading day the plan was generated (today, by definition).
    generated_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    symbol = Column(String(10), nullable=False, index=True)
    direction = Column(String(32), nullable=False)        # LONG / SHORT / NEUTRAL
    bias = Column(String(32), nullable=False)             # momentum / mean-reversion

    # Plan levels
    entry_low = Column(Float, nullable=False)
    entry_high = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    tp1 = Column(Float, nullable=False)
    tp2 = Column(Float, nullable=False)
    rr_tp1 = Column(Float, nullable=False)
    rr_tp2 = Column(Float, nullable=False)
    preferred_window = Column(String(128), nullable=False, default="")
    position_lots = Column(Integer, nullable=False, default=0)
    thesis = Column(Text, nullable=False, default="")

    # Reference context (from the IntradayProfile at generation time)
    score = Column(Float, nullable=False)
    sector = Column(String(64), nullable=False, default="")
    last_close = Column(Float, nullable=False)
    adv_3m = Column(Float, nullable=False)
    avg_day_range_pct = Column(Float, nullable=False)
    beta = Column(Float, nullable=True)
    ret_1m = Column(Float, nullable=False)

    # Optional link to the parent report (one report = N plans)
    report_id = Column(String(64), nullable=True, index=True)

    outcome = relationship(
        "IntradayOutcomeRow",
        back_populates="plan",
        uselist=False,
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        # One plan per (symbol, plan_date) so re-running the same day is idempotent.
        UniqueConstraint("symbol", "plan_date", name="uq_intraday_plan_symbol_date"),
        Index("ix_intraday_plans_date_symbol", "plan_date", "symbol"),
    )

    def __repr__(self) -> str:
        return f"<IntradayPlan {self.symbol} {self.plan_date} {self.direction}>"


class IntradayOutcomeRow(Base):
    """Outcome of one plan, filled in after the next trading session closes.

    outcome codes:
      "TP2"  - price hit TP2 before SL (full winner)
      "TP1"  - price hit TP1 before SL but not TP2 (partial winner, conservative)
      "SL"   - stop-loss was hit first
      "EOD"  - end of day, neither TP nor SL hit (scratch / breakeven)
      "OPEN_GAP" - stock opened outside entry zone AND outside SL in a way that
                   invalidates the plan (we treat the open as the fill and
                   evaluate from there)
      "NO_DATA" - no next-day OHLC available (market holiday, ticker delisted)
    """

    __tablename__ = "intraday_outcomes"

    id = Column(Integer, primary_key=True)
    plan_id = Column(
        Integer,
        ForeignKey("intraday_plans.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )
    eval_date = Column(Date, nullable=False, index=True)   # session we evaluated
    open_price = Column(Float, nullable=True)
    high_price = Column(Float, nullable=True)
    low_price = Column(Float, nullable=True)
    close_price = Column(Float, nullable=True)
    outcome = Column(String(16), nullable=False)
    r_multiple = Column(Float, nullable=False, default=0.0)  # realized R
    pnl_per_lot_idr = Column(Float, nullable=False, default=0.0)
    notes = Column(Text, nullable=False, default="")
    evaluated_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    plan = relationship("IntradayPlanRow", back_populates="outcome")

    def __repr__(self) -> str:
        return f"<IntradayOutcome {self.plan_id} {self.outcome} R={self.r_multiple:.2f}>"


__all__ = ["IntradayPlanRow", "IntradayOutcomeRow"]
