"""Markdown report generator for the intraday module.

Output style intentionally mirrors the user's May 2026 intraday report
(`E:\project\stockai\reports\idx_intraday_202605.md`) so the generated
artifact can sit next to the manual research without looking out of place.
"""

from __future__ import annotations

from datetime import date

from stockai.intraday.scoring import IntradayProfile
from stockai.intraday.planner import IntradayPlan, generate_plan, DEFAULT_CAPITAL_IDR


def _fmt_idr(x: float) -> str:
    return f"{x:,.0f}"


def _fmt_pct(x: float, digits: int = 2) -> str:
    return f"{x*100:.{digits}f}%"


def _fmt_signed_pct(x: float, digits: int = 2) -> str:
    return f"{x*100:+.{digits}f}%"


def _score_bar(score: float) -> str:
    """Render a 0-10 score as a 10-cell Unicode bar."""
    full = int(round(score))
    return "█" * full + "░" * (10 - full)


def render_report(
    profiles: list[IntradayProfile],
    *,
    as_of: date | None = None,
    capital_idr: float = DEFAULT_CAPITAL_IDR,
    title: str = "IDX Intraday Trading Plan",
) -> str:
    """Render a markdown report for the given profiles.

    Args:
        profiles:   list of scored profiles (already sorted desc by score).
        as_of:      report date. Defaults to today.
        capital_idr: capital base for position sizing hints.

    Returns:
        A markdown string ready to write to disk.
    """
    as_of = as_of or date.today()
    lines: list[str] = []

    lines.append(f"# {title} — {as_of.isoformat()}")
    lines.append("")
    lines.append(
        f"**Universe screened:** LQ45 / IDX30 (per `stockai.data.sources.idx`).  "
        f"**Data:** yfinance daily OHLCV (6M window).  "
        f"**Generated by:** `stockai intraday report`."
    )
    lines.append("")
    lines.append(
        "**Methodology:** composite intraday score (0-10) = "
        "0.30·liquidity + 0.30·volatility + 0.15·spread + 0.15·beta + 0.10·momentum. "
        "Mirrors the scoring in `reports/idx_intraday_202605.md` so this output "
        "is directly comparable to the manual research."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # ----- 1. Summary table ------------------------------------------------
    lines.append("## 1. Summary — Top Intraday Candidates")
    lines.append("")
    lines.append(
        "| Rank | Ticker | Sector | Close (IDR) | 1W % | 1M % | ADV (M sh) | Day Range % | Score |"
    )
    lines.append(
        "|------|--------|--------|-------------|------|------|------------|-------------|-------|"
    )
    for i, p in enumerate(profiles, start=1):
        lines.append(
            f"| {i} | **{p.symbol}** | {p.sector} | {_fmt_idr(p.last_close)} | "
            f"{_fmt_signed_pct(p.ret_1w)} | {_fmt_signed_pct(p.ret_1m)} | "
            f"{p.adv_3m/1e6:.1f} | {_fmt_pct(p.avg_day_range_pct)} | "
            f"**{p.score:.1f}** |"
        )
    lines.append("")

    # ----- 2. Per-name score breakdown -------------------------------------
    lines.append("## 2. Per-Name Score Breakdown")
    lines.append("")
    lines.append(
        "| Ticker | Liquidity (3.0) | Volatility (3.0) | Spread (1.5) | Beta (1.5) | Momentum (1.0) | Composite |"
    )
    lines.append(
        "|--------|------------------|-------------------|--------------|------------|----------------|-----------|"
    )
    for p in profiles:
        weighted = (
            0.30 * p.sub_liquidity
            + 0.30 * p.sub_volatility
            + 0.15 * p.sub_spread
            + 0.15 * p.sub_beta
            + 0.10 * p.sub_momentum
        )
        lines.append(
            f"| {p.symbol} | {p.sub_liquidity:.1f} | {p.sub_volatility:.1f} | "
            f"{p.sub_spread:.1f} | {p.sub_beta:.1f} | {p.sub_momentum:.1f} | "
            f"**{weighted:.2f}** |"
        )
    lines.append("")

    # ----- 3. Per-name plan ------------------------------------------------
    lines.append("## 3. Per-Name Next-Day Plan")
    lines.append("")
    for p in profiles:
        plan = generate_plan(p, capital_idr=capital_idr)
        lines.extend(_render_plan_section(plan, p, capital_idr))
        lines.append("")

    # ----- 4. How to use ---------------------------------------------------
    lines.append("## 4. How To Use This Report")
    lines.append("")
    lines.append(
        "1. **Run before 09:00 WIB** so the plan is in front of you at the open.\n"
        "2. **Momentum names** (high 1M return, high day range) — trade with the "
        "morning flow, take profit at TP1, trail the rest to TP2.\n"
        "3. **Mean-reversion names** (low beta, deep liquidity) — wait for "
        "≥1% deviation from VWAP on heavy volume, then fade back.\n"
        "4. **Position size is the 2% rule** at the bottom of each plan; if it "
        "shows 0 lots the R/R is too thin — skip the trade.\n"
        "5. **Always honor the stop-loss.** A plan that doesn't work at 2R is "
        "still useful as research, not as a position."
    )
    lines.append("")

    # ----- 5. Risks / caveats --------------------------------------------
    lines.append("## 5. Risks & Caveats")
    lines.append("")
    lines.append(
        "- This module uses **daily OHLCV** (yfinance). True intraday backtest "
        "requires a paid tick feed (RTI, IDX Data, Stockbit Pro, broker API).\n"
        "- **Outlier months distort the picture.** A name with a 30%+ 1M move "
        "may be in price-discovery mode, not a clean trend continuation.\n"
        "- **Beta is from yfinance `info`** and is 5Y monthly; it can lag real "
        "regime changes by months. Treat the sub-score as a hint, not a fact.\n"
        "- **Lot sizes vary** for some names (e.g. BREN, AMMN traded in 1 share "
        "since 2024 via fractional lots). The 100-share default is a safe "
        "conservative assumption.\n"
        "- **IDX session structure:** pre-open 08:30-09:00, session 1 "
        "09:00-12:00, break 12:00-13:30, session 2 13:30-15:59, closing "
        "auction 15:59-16:00 (all WIB). Plans assume round-trip inside one day."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        f"*Generated {as_of.isoformat()} by `stockai intraday report`. "
        "For research/educational use only — not investment advice.*"
    )
    lines.append("")
    return "\n".join(lines)


def _render_plan_section(
    plan: IntradayPlan, profile: IntradayProfile, capital_idr: float
) -> list[str]:
    """Render one plan section (used as a helper for the main report)."""
    out: list[str] = []
    score_bar = _score_bar(profile.score)
    out.append(f"### {plan.symbol} — {plan.direction}")
    out.append("")
    out.append(
        f"- **Sector:** {profile.sector}  "
        f"- **Score:** `{profile.score:.2f} / 10` `{score_bar}`"
    )
    out.append(
        f"- **Last close:** Rp {_fmt_idr(profile.last_close)}  "
        f"- **1M return:** {_fmt_signed_pct(profile.ret_1m)}  "
        f"- **Beta:** {profile.beta if profile.beta is not None else 'n/a'}"
    )
    out.append(
        f"- **ADV (3M):** {profile.adv_3m/1e6:.1f} M sh "
        f"(~Rp {profile.turnover_idr_3m/1e9:.1f} bn turnover)  "
        f"- **Avg day range:** {_fmt_pct(profile.avg_day_range_pct)}"
    )
    out.append("")
    out.append("**Trade plan**")
    out.append("")
    out.append(f"- Direction: **{plan.direction}** ({plan.bias})")
    out.append(
        f"- Entry zone: **Rp {_fmt_idr(plan.entry_zone_low)} – Rp {_fmt_idr(plan.entry_zone_high)}**"
    )
    out.append(f"- Stop-loss: **Rp {_fmt_idr(plan.stop_loss)}**")
    out.append(f"- TP1: **Rp {_fmt_idr(plan.tp1)}** (R/R = {plan.rr_ratio_tp1:.2f})")
    out.append(f"- TP2: **Rp {_fmt_idr(plan.tp2)}** (R/R = {plan.rr_ratio_tp2:.2f})")
    out.append(f"- Preferred window: {plan.preferred_window}")
    out.append(
        f"- Position size (2% rule, capital Rp {_fmt_idr(capital_idr)}): "
        f"**{plan.position_lots} lot** ({plan.position_lots * 100} sh)"
    )
    out.append("")
    out.append(f"> {plan.thesis}")
    for n in plan.notes:
        out.append(f"> ⚠️ {n}")
    out.append("")
    return out


__all__ = ["render_report"]
